AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Contains a simple database

Resources:
  Database:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
Outputs:
  DatabaseArn:
    Description: "Database arn"
    Value: !GetAtt Database.Arn
