distributionName: attini-runner-demo
initDeployConfig:
  forceUpdate: true
  template: deployment-plan.yaml
  stackName: ${environment}-${distributionName}-deployment-plan

package:
  prePackage:
    commands:
      - attini configure set-dist-id --random
