AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AttiniDeploymentPlan
  - AWS::Serverless-2016-10-31

Resources:
  CustomRunner:
    Type: Attini::Deploy::Runner
    Properties:
      Image: public.ecr.aws/amazonlinux/amazonlinux:latest
      Startup:
        Commands:
          - yum install jq -y
      RunnerConfiguration:
        IdleTimeToLive: 600

  RunnerDemo:
    Type: Attini::Deploy::DeploymentPlan
    Properties:
      DeploymentPlan:
        - Name: PassLyrics
          Type: AttiniRunnerJob
          Properties:
            Runner: CustomRunner
            Commands:
               - echo  "Never gonna give you up!" > ${ATTINI_OUTPUT}
        - Name: SingLyrics
          Type: AttiniRunnerJob
          Properties:
            Runner: CustomRunner
            Commands:
              - bash sing-script.sh




